### ISSUE TITLE
Recalling .wixrc

### ISSUE THREAD

**Issue by matteofranceschini** [nbarikipoulos/wix-msi#22]
Hi! I love your work, thank you for this tool!

I have a question: when I save the .wixrc file with my settings, I supposed that the next call would automatically load it to get the full setup, but it only loads the UUID: am I doing something wrong?

The first time I call the program with this command
`wix-msi myProgram -i X:\img\icon.ico -b X:\img\banner.png -B X:\img\background.png -s`

it correctly saves

```
{
  "myProgram": {
    "uuid": "the correct UUID",
    "ico": "X:\\img\\icon.ico",
    "banner": "X:\\img\\banner.png",
    "background": "X:\\img\\background.png"
  }
}
```

But when I call `wix-msi myProgram` the next time, the log shows that the default images are being loaded (but the UUID is preseved!)... why is this?

thanks!

**Comment by nbarikipoulos** [comment]
Hi,

Use relative path as mentioned in documentation. I even do not expect - aka have tested - that it could work with absolute path,

Then, yes there is something wrong, the validation step should raise an error when absolute path are used/ or may be I should fix it but I am not a really big fan of absolute path, especially here: "common" use case is to have everything located in the same place aka inside the module (wixrc on the top of the module - mandatory to access to the package.json, images in a forlder inside the module.)

**Comment by matteofranceschini** [comment]
I'm not a big fan of absolute paths, too :D 

I thought it was necessary due to the fact that if I use the command like this
`wix-msi MarcoPrinter -i .\img\icon.ico -b .\img\banner.png -B .\img\background.png -s`

`**C:\Users\myuser\AppData\Roaming\npm\node_modules\wix-msi**\img\icon.ico`
` File does not exist`
Part of the problem may be that it's the first time I'm dealing with windows and programming and I may have done something wrong.

OT: I'm trying to make my program work with [node-windows](https://github.com/coreybutler/node-windows) to have it running as a service with autostart. It's obviously not working (as said, I'm at my first try :D ) but I guess it's because I may need to _package_ other files into the msi, so that when it's installed they're copied into the program directory, too. Is it possible to achieve this with your tool?

**Comment by nbarikipoulos** [comment]
No problem, 

Maybe check my [poppy-robot-cli](https://github.com/nbarikipoulos/poppy-robot-cli) project, it will be clearer. Note I refer the wix-msi project as optional dependency to avoid to "contaminate" the project with win32 and x64 for target os and architecture.

U can use the following command too:
``
npx wix-msi MarcoPrinter
``
It allows to not have wix-msi installed globally and then, U will not have to re-install it globally each time U change of node release.

**Comment by nbarikipoulos** [comment]
My mistake, there is effectively a bug loading wixrc file.
If:
- An option has a default value (such as images),
- User does not set it by cli,

Then the  default value will be used despite the data in the rc file.
