### ISSUE TITLE
Not able run wix-msi 

### ISSUE THREAD

**Issue by sm185360** [nbarikipoulos/wix-msi#44]
I am getting below error when running `wix-msi target_bin`
`> Check input data
ERROR name: 'target_bin'
  Bin not found in package.json/bin
OK uuid: 'fedda0f1-f002-4a86-b1f9-9cb0d5fa9620'
OK version: '1.10.0'
OK exe: 'target_bin'
ERROR entry: 'undefined'
  Check name option aka target bin in package.json
OK author: ''
OK homepage: 'undefined'
OK license: 'true'
INFO licenseSourceFile: 'undefined'
  Unable to find LICENSE or LICENCE.md file. License page will be skipped
OK icon: 'node_modules\wix-msi\assets\icon.png'
OK banner: 'm\node_modules\wix-msi\assets\banner.png'
OK background: '\node_modules\wix-msi\assets\background.png'
OK color: 'white'
OK dir: 'build'
OK useFiles: 'false'
Aborted: found error(s) in input`

package.json has bin

`{
  "name": "posmonitorservice",
  "version": "1.10.0",
  "description": "posmonitorservice",
  "main": "dist/main.js",
  "bin": {
    "posmonitorservice": "dist/main.js"
  },
}`

Do I need to add any additional things to package.json?

**Comment by nbarikipoulos** [comment]
Hi,
try:
```
wix-msi posmonitorservice
```
aka use the name of your bin entry.
Next, have a look to this issue #41 : author field is mandatory. If U leave an empty field, the packaging step will failed. Note It will be fixed on next release. 

Let me know if it solves your issue.
N.
